version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - /home/appserver/mongodb:/data/db
    ports:
      - 27017:27017
  springboot-mongodb:
    image: spring-boot-mongo-app
    container_name: springboot-mongodb
    ports:
      - 8080:8080
    links:
      - mongodb